#ifndef PLAYER_INTERNAL_H
#define PLAYER_INTERNAL_H

#include "theme.h"

#define PANEL_WIDTH               520

#define CHOICE_PANEL_HEIGHT       460
#define CHOICE_PANEL_ABOVE_CENTRE 130
#define CHOICE_TITLE_INSIDE_Y      32
#define CHOICE_TITLE2_INSIDE_Y     96
#define CHOICE_FRIENDLY_INSIDE_Y  142
#define CHOICE_DIVIDER_INSIDE_Y   188
#define CHOICE_SUBTITLE_INSIDE_Y  222
#define CHOICE_BTN1_INSIDE_Y      250
#define CHOICE_BTN_GAP             24

#define NEW_PANEL_HEIGHT           320
#define NEW_PANEL_ABOVE_CENTRE     120
#define NEW_TITLE_INSIDE_Y          28
#define NEW_DIVIDER_INSIDE_Y        52
#define NEW_INPUT_INSIDE_Y          68
#define NEW_INPUT_HEIGHT             42
#define NEW_CONFIRM_BTN_GAP         24

#define BACK_BTN_X        THEME_MARGIN
#define BACK_BTN_Y        (THEME_MARGIN + 8)
#define BACK_BTN_WIDTH    110
#define BACK_BTN_HEIGHT   THEME_BTN_H_SMALL

#define OLD_HEADER_HEIGHT   120
#define OLD_FOOTER_HEIGHT   20
#define OLD_ROW_HEIGHT      (THEME_BTN_H + 18)
#define OLD_FIRST_ROW_Y     108
#define OLD_MIN_PANEL_TOP   20

#define MINION_LEFT_X       60
#define MINION_RIGHT_OFFSET 60
#define MINION_ABOVE_ROAD   42

#define BTN_WIDTH    (PANEL_WIDTH - 40)
#define BTN_HEIGHT   THEME_BTN_H

#define OLD_COLUMN_COUNT 2
#define OLD_CELL_GAP    18
#define OLD_CELL_PADDING 8
#define OLD_CELL_WIDTH  ((BTN_WIDTH - OLD_CELL_GAP) / OLD_COLUMN_COUNT)
#define OLD_DELETE_BTN_WIDTH 50
#define OLD_ROW_LABEL_WIDTH (OLD_CELL_WIDTH - OLD_DELETE_BTN_WIDTH - OLD_CELL_PADDING)

#define MAX_SAVED_PLAYERS  100

#endif
